### Get all contacts
GET http://localhost:3000/contacts HTTP/1.1

### Get a single contact by ID (Contact1)
GET http://localhost:3000/contacts/678add31235a27e2ec7f0b13 HTTP/1.1

### Get a single contact by ID (Contact2)
GET http://localhost:3000/contacts/678aedd4806b1bdcbc2cc156 HTTP/1.1

### Get a single contact by ID (Contact3)
GET http://localhost:3000/contacts/678af359f2c19eb8758bdbf0 HTTP/1.1

### Create a new contact
POST http://localhost:3000/contacts/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Hello333",
  "lastName": "Doe333",
  "email": "HelloDoe333@example.com",
  "favoriteColor": "Blue",
  "birthday": "1994-08-26"
}

### Update a contact (Bob)
PUT http://localhost:3000/contacts/678b1b131120709fc3cd4088 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Test8",
  "lastName": "Examples",
  "email": "test5@example.com",
  "favoriteColor": "Blue",
  "birthday": "1994-08-26"
}

### Delete a contact (Contact Created)
DELETE http://localhost:3000/contacts/678b2184dfe372929e6318e3 HTTP/1.1
